//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fired //: Employee
    {
        public int Id { get; set; }
        public string ФИО { get; set; }
        public string Департамент { get; set; }
        public string Должность { get; set; }
        public string Категория { get; set; }
    }
}
